### ISSUE TITLE
Cannot see the public facing demo site

### ISSUE THREAD

**Issue by cprcrack** [payloadcms/public-demo#21]
Navigating to https://demo.payloadcms.com redirects to https://demo.payloadcms.com/admin.

I want to see how the site looks when not logged in as an admin, is that not possible?

**Comment by jacobsfletch** [comment]
Hey @cprcrack! This demo is actually purely aa demonstration of Payload and does not include a front-end. ALTHOUGH we are actively working on building one 😎. I am going to close this issue for now but feel free to use this thread for updates. We do have many examples of how to build front-ends for Payload here: https://github.com/payloadcms/payload/tree/master/examples but also our own website 
 here: https://github.com/payloadcms/website
