### ISSUE TITLE
Not working video button in richText editor

### ISSUE THREAD

**Issue by yagee** [payloadcms/public-demo#9]
Hello!

Thanks for the great CMS and demo!

## Steps to reproduce:
1. Open any post on public demo: https://demo.payloadcms.com/admin/collections/posts/
2. Try to edit content in richText editor by pressing 'video' button.

![image](https://user-images.githubusercontent.com/1481199/190922436-348739aa-fd38-457c-ad37-98f2ecf8ff9c.png)

This causes a new tab with error message:

![image](https://user-images.githubusercontent.com/1481199/190922494-44864c8c-65aa-4159-bff0-018761958286.png)

**Comment by jmikrut** [comment]
@yagee thank you for reporting this! It was an updated package that was no longer working properly.

Fixed!
